apiVersion: v1
kind: Service
metadata:
    name: back-end
spec:
  type: ClusterIP # default
  ports:
   - targetPort: 80 # target pod port
     port: 80   # service port
# which pod to connect
  selector:
     app: myapp
     type: front-end
