apiVersion: v1
kind: Pod
metadata:
 name: myapp-pod
 labels:
    app: myapp
    type: front-end
spec:
  containers:
   - name: nginx-container
     image: nginx
tolerations:
- key: app
  operator: "equal"
  value: web
  effect: NoSchedule

# kubectl taint nodes node01 app=web:Noschedule
